name: General Release
description: 'A simple action that has an option to toggle `include administrators` on branch protection, and then run semantic-release with a given release config'
inputs:
  token:
    description: 'git token to use for the run'
    required: true
  toggle-admins:
    description: 'If true, this action will disable the `include administrators` setting in branch protection for this branch, and re-enable it after release. Re-enabling is run using always()'
    required: false
    default: false
  release-config:
    description: 'The release configuration to use for the release. Set this to `@swarm-io/release-config-javascript-actions` for javascript actions'
    required: false
    default: '@swarm-io/release-config-general'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
    - uses: swarm-io/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true'
      with:
        token: ${{ inputs.token }}
        include-admins: false
    - id: semantic-release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        extends: ${{ inputs.release-config }}
    - uses: swarm-io/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true' && always()  # Force to always run this step to ensure "include administrators" is always turned back on
      with:
        token: ${{ inputs.token }}
        include-admins: true